# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeagregaunapeliculaparacadadirector():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seagregaunapeliculaparacadadirector(self):
    # Test name: se agrega una pelicula para cada director
    # Step # | name | target | value | comment
    # 1 | close |  |  | 
    self.driver.close()
    # 2 | open | / |  | 
    self.driver.get("http://localhost:3000/")
    # 3 | setWindowSize | 1505x803 |  | 
    self.driver.set_window_size(1505, 803)
    # 4 | click | id=:r1:-tab-0 |  | 
    self.driver.find_element(By.ID, ":r1:-tab-0").click()
    # 5 | click | css=#add-movie-btn .w-16 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn .w-16").click()
    # 6 | click | id=title |  | 
    self.driver.find_element(By.ID, "title").click()
    # 7 | type | id=title | movie 1 | 
    self.driver.find_element(By.ID, "title").send_keys("movie 1")
    # 8 | type | id=description | test desc | 
    self.driver.find_element(By.ID, "description").send_keys("test desc")
    # 9 | type | id=year | 2022 | 
    self.driver.find_element(By.ID, "year").send_keys("2022")
    # 10 | select | id=director_id | label=test 1 | 
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = 'test 1']").click()
    # 11 | click | css=.h-min > .flex |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 12 | click | css=#add-movie-btn .w-16 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn .w-16").click()
    # 13 | click | id=title |  | 
    self.driver.find_element(By.ID, "title").click()
    # 14 | type | id=title | movie 2 | 
    self.driver.find_element(By.ID, "title").send_keys("movie 2")
    # 15 | type | id=description | test desc 2 | 
    self.driver.find_element(By.ID, "description").send_keys("test desc 2")
    # 16 | click | id=year |  | 
    self.driver.find_element(By.ID, "year").click()
    # 17 | type | id=year | 2023 | 
    self.driver.find_element(By.ID, "year").send_keys("2023")
    # 18 | click | id=director_id |  | 
    self.driver.find_element(By.ID, "director_id").click()
    # 19 | select | id=director_id | label=test 2 | 
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = 'test 2']").click()
    # 20 | click | css=.h-min > .flex |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
  
