# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeagregan2directores():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seagregan2directores(self):
    # Test name: Se agregan 2 directores
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1936x1048 |  | 
    self.driver.set_window_size(1936, 1048)
    # 3 | click | id=:r1:-tab-1 |  | 
    self.driver.find_element(By.ID, ":r1:-tab-1").click()
    # 4 | click | css=#add-director-btn path |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-director-btn path").click()
    # 5 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 6 | type | id=name | test 1 | 
    self.driver.find_element(By.ID, "name").send_keys("test 1")
    # 7 | click | css=.h-min > .flex |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 8 | click | css=#add-director-btn path |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-director-btn path").click()
    # 9 | mouseOver | css=#add-director-btn path |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#add-director-btn path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | mouseOut | css=#add-director-btn path |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 11 | click | id=name |  | 
    self.driver.find_element(By.ID, "name").click()
    # 12 | type | id=name | test 2 | 
    self.driver.find_element(By.ID, "name").send_keys("test 2")
    # 13 | click | css=.h-min > .flex |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 14 | click | id=:r1:-tab-0 |  | 
    self.driver.find_element(By.ID, ":r1:-tab-0").click()
    # 15 | click | css=#add-movie-btn path |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn path").click()
  
