version: '3'
services:
  movies-front:
    # completa esta seccion, lee el archivo README en la carpeta movies-front-OK
    build:
      context: ./movies-front/
      dockerfile: Dockerfile
    volumes:
      - ./movies-front:/usr/app
      - /usr/app/node_modules
    environment:
      - REACT_PORT=${REACT_PORT}
      - REACT_APP_API_URI= ${REACT_APP_API_URI}
    depends_on: 
      - movies-api
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    expose: 
      - ${REACT_PORT}
    command: npm start
    # de que servicio depende el frontend? OK
   
  movies-api:
    depends_on:
      - postgres
    build:
      context: ./movies-api/
      target: build-release-stage
      dockerfile: Dockerfile
    restart: always
    expose:
      - ${BIND_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - BIND_IP=${BIND_IP}
      - BIND_PORT=${BIND_PORT}
    ports:
      - ${BIND_PORT}:${BIND_PORT}
    command: /movies-api -b ${BIND_IP} -p ${BIND_PORT}

  postgres:
    image: postgres:15.3
    restart: always
    container_name: postgresBD
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}

  flyway:
    image: flyway/flyway:latest
    container_name: migration_flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_GROUP=true
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_migrations:/flyway/sql
    depends_on:
      - postgres
