// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Caso 2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Caso 2', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 550, height: 691 })
    await driver.findElement(By.css("#add-movie-btn path")).click()
    {
      const element = await driver.findElement(By.css("#add-movie-btn path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("El risas")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Una risa constante")
    await driver.findElement(By.id("year")).click()
    await driver.findElement(By.id("year")).sendKeys("2025")
    {
      const element = await driver.findElement(By.id("director_id"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("director_id"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("director_id"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("director_id")).click()
    {
      const dropdown = await driver.findElement(By.id("director_id"))
      await dropdown.findElement(By.xpath("//option[. = 'Juan Perez Director']")).click()
    }
    await driver.findElement(By.css("option:nth-child(13)")).click()
    await driver.findElement(By.css(".h-min > .flex")).click()
    await driver.findElement(By.css("#add-movie-btn .w-16")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("El bromas")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Broma en pañales")
    await driver.findElement(By.id("year")).click()
    await driver.findElement(By.id("year")).sendKeys("2024")
    await driver.findElement(By.id("director_id")).click()
    {
      const dropdown = await driver.findElement(By.id("director_id"))
      await dropdown.findElement(By.xpath("//option[. = 'El directors']")).click()
    }
    await driver.findElement(By.css("option:nth-child(14)")).click()
    await driver.findElement(By.css(".h-min > .flex")).click()
  })
})
