// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Caso 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Caso 1', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 550, height: 691 })
    await driver.findElement(By.id(":r1:-tab-1")).click()
    await driver.findElement(By.css("#add-director-btn .w-16")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Juan Perez Director")
    await driver.findElement(By.css(".h-min > .flex")).click()
    await driver.findElement(By.css("#add-director-btn path")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("El directors")
    await driver.findElement(By.css(".h-min > .flex")).click()
  })
})
